### PR TITLE
Accessibility Data Updates

### PR DESCRIPTION
**Pull request by xtine**
**Accessibility pages**
* Updated datasets for Agencies and Domains
* Descriptions of errors on a11y pages
* Average errors per page on Domain page

### CODE REVIEW

**Comment by konklone** [comment]
For the record (and my own understanding), where's the code that calculated these data updates from the raw domain-scan output?

**Comment by xtine** [comment]
It's @jtexnl's data wrangling.

**Comment by konklone** [comment]
@jtexnl Could you at least put a link to a gist of your code in this PR, so we have some documented reference to how this was done?

**Comment by jtexnl** [comment]
Sure; I'm working on a cleaner version this weekend, but here's the working code as it exists:
https://gist.github.com/jtexnl/031d409977365e2c00823d2cb13b2135

**Comment by konklone** [comment]
Thanks, @jtexnl. I'll leave it to someone more familiar with this code to merge, but looks good to me.

**Comment by jtexnl** [comment]
@adelevie could you have a look at this PR before merge? I'd like to have a second set of eyes on the data from someone who's pretty familiar with it.

**Pull request merged**
