### PR TITLE
Fix/details btn

### PR DESCRIPTION
**Pull request by nickbristow**
Details btn controllable by keyboard

### CODE REVIEW

**Comment by konklone** [comment]
This doesn't appear to work for me, on my keyboard. Is `13` a reliable key code? Can you post some more details or a screenshot of what I should expect to see?

Also, as submitted, this only covers the HTTPS table, and only the domains tab.

**Comment by nickbristow** [comment]
@konklone this is a pretty hacky solution honestly, but i thought the HTTPS table domain tab, was the only table with those plus detail buttons. When tabbing you should see this
pulse___https_in_the_federal_government_-_all_domains

Hitting enter should trigger it showing the detailed info line.

**Comment by konklone** [comment]
Gotcha. That makes sense, but I'm not able to trigger the effect on my Dell XPS. I'll merge for now on your assurances it works on Macs, since this is a high priority item, but let's put our heads together soon on a more complete fix.

**Comment by nickbristow** [comment]
Sounds good.

On Tuesday, June 2, 2015, Eric Mill <notifications@github.com> wrote:

> Merged #200 <https://github.com/18F/pulse/pull/200>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/pulse/pull/200#event-320555420>.
>


-- 
Nick Bristow
18f <http://18f.gsa.gov> Innovation Specialist
Nick.Bristow@gsa.gov

**Pull request merged**
