### PR TITLE
Update data

### PR DESCRIPTION
**Pull request by nickbristow**
Fixes agencies scan

### CODE REVIEW

**Comment by nickbristow** [comment]
cc @gbinal

**Comment by konklone** [comment]
@nickbristow For archival purposes, can you put the date of the scan in this PR somewhere, as a comment or by editing the title/description?

**Comment by gbinal** [comment]
This data should be from Aug. 5 (correcting #484, #485, and #493)

**Comment by nickbristow** [comment]
@gbinal @konklone 

Its actually august 4th, 2016 Gray

**Comment by acdha** [comment]
One thought: it might be a lot easier to review and track changes if the JSON file was run through something like `python -mjson.tool` before committing.

**Comment by gbinal** [comment]
Thanks, @acdha.  Great point.  I've got to go ahead and get this one out, but in the future, agree that'll be helpful.  

I spotchecked the data and am going to go ahead and merge.

**Comment by gbinal** [comment]
Assigning to @konklone and requesting these all be pushed to staging.

**Comment by konklone** [comment]
Deployed.

**Pull request merged**
