### PR TITLE
Move to new central DAP hosting location

### PR DESCRIPTION
**Pull request by konklone**
Moving the DAP snippet away from `analytics.usa.gov` (which is running 2.01 now) and to `dap.digitalgov.gov`.

Looking to @smarina04 or @tdlowden for a :+1: here. I figure it's worth having this site be an exemplar, since we're measuring participation.

### CODE REVIEW

**Comment by smarina04** [comment]
@konklone hold off on that for a few days before making this change. The internal contracts stuff needs to happen first before we can roll out officially,

**Comment by konklone** [comment]
@smarina04 No problem.

**Comment by konklone** [comment]
@smarina04 I assume we're good to merge this in now?

**Comment by smarina04** [comment]
Yep, it should be merged.

**Comment by konklone** [comment]
Done, thanks for the :eyes: @smarina04.

**Pull request merged**
