### PR TITLE
508 Issues

### PR DESCRIPTION
**Pull request by xtine**
#### Fixing 508 issues
For _508 Issues from GSA_ #408 

Done:
* empty alt on flag icon
* only h1 on page, updated header hierarchy
* captions for tables
* label for search box
* onclick attribute for skipnav
* roles for `banner`, `nav`, `main`, `contentinfo`
* title matches h1

### CODE REVIEW

**Comment by xtine** [comment]
I need guidance from @nickbristow on how to tackle:
- tab links
- how to address 200% zoom on table
- making 10|25|50 keyboard accessible
- regaining focus on checkboxes and column heading links

**Comment by xtine** [comment]
Also I am having a difficult time getting the first column rows that are `scope=row` to be TH instead of TD... trying to change it seems to break the the click to expand child row feature. I need assistance on how I should proceed in trying to either hack it or if it's accessible to not fix.

**Comment by nickbristow** [comment]
@xtine 
- Table: The table just needs to not be cut off or overlapping at 200% zoom. It was fine in chrome because it had horizontal scroll bars. I emailed the person that did the report to see what his issue was, or if it was browser specific.
- Tab Links: tab links should have `role='tab' aria-controls='tab-panel-id' aria-selected='true/false'` tab panels should have `role='tabpanel' aria-hidden='true/false"` the list should have `role='tablist'` 
- 10|25|100: these just need to accept keyboard focus, try giving them `tabindex='0'`
- checkboxes: I'm not sure what I meant by this, i dont see any on the page.

**Comment by nickbristow** [comment]
In certain browsers the table is cut off and you can't scroll to the content, we should develop a "mobile" view for when the screen gets too narrow. The example provided by the reviewer http://promotions.usa.gov/platform/registration-deadline.html

**Comment by xtine** [comment]
Got tab roles and aria attributes in, as well as keyboard focusable page length controls.

**Comment by nickbristow** [comment]
Adding these here so I can check off the ones I verified

- [ ]  Use empty alt tag on flag icon
- [ ] Multiple h1's used on the page
- [ ] First row in table with scope = row should be TH, not TD
- [ ] Table doesn't have a caption
- [ ]  Search box doesn't have explicit lable (label for= )
- [ ] use `onclick="document.getElementById('target').focus()"` on skip nav
- [ ] Tab links need to be programmed like tabs
- [ ] table breaks at 200% zoom
- [ ] Show 10|25|50 entries isn't keyboard accessible
- [ ] Loss of focus on checkboxes and column heading links
- [ ] banner needs `role="banner"`
- [ ] nav needs `role="nav"`
- [ ] Page needs `role="main"`
- [ ] Footer needs `role='contentinfo'`
- [ ] h1 should match page title

**Comment by xtine** [comment]
I've updated all the issues I can. Not sure what to do about the th/td thing as for the click to expand row functionality to work using the dataTables library, as it won't work if changed to a th.

**Comment by nickbristow** [comment]
👍

**Comment by jtexnl** [comment]
@nickbristow are we good to merge here? I need to get this checked by Dave Stenger once it's all live on the staging site.

**Comment by nickbristow** [comment]
@jtexnl there are two issues, but we don't really have fixes for them ATM. Everything else is good to go.

**Comment by gbinal** [comment]
I'd suggest we push what we have, and recheck our work.

**Comment by jtexnl** [comment]
Alright, I'm going to go ahead and merge, then have Dave check over everything tomorrow and see if he has any ideas.

**Pull request merged**
