### PR TITLE
Link number of agency domains to a filtered list of their domains

### LINKED ISSUE #101: enable permalinks
I'm guessing this isn't readily doable for launch, but it would be great if every page customization (number of entries shown, what page of results you're on, sorting) all changed the URL so that permalinks were available by default.

### PR DESCRIPTION
**Pull request by konklone**
This adds permalink support for search filters, and uses this feature to add support for filtering domains by agency.

image

Clicking the HHS domain number will take you to `/https/domains/#q=Department%20of%20Health%20And%20Human%20Services`, which shows the list of domains filtered to those owned by HHS.

Fixes #101, and #118.

### CODE REVIEW

**Comment by juliaelman** [comment]
Made one small nitpicky change to from link to filter. I tried out filtering out the agencies listed to the agencies tab, but not entirely sure that made a lot of sense to do. Possibly for another PR, but wanted to get your thoughts on whether or not it's necessary.

**Comment by konklone** [comment]
> I tried out filtering out the agencies listed to the agencies tab, but not entirely sure that made a lot of sense to do. Possibly for another PR, but wanted to get your thoughts on whether or not it's necessary.

Sorry, I don't understand what you mean. Can you explain a bit more?

**Comment by juliaelman** [comment]
With this pull request you are able to go from `analytics/agencies/`, click on the number of domains and get a list of filtered domains by agency at `analytics/domains/#q=`.

My thought was to make the Agency name clickable on `/analytics/domains/` and filter to the Agency tab with that particular agency. See screenshot for where the link would be:

screen shot 2015-05-29 at 11 26 56 am

**Comment by konklone** [comment]
Ooooh. Yes, the thought had occurred to me too. My reaction is that it's nice, but also a lot easier to fit into the DAP table than the crowded HTTPS table, so I hadn't prioritized it.

**Pull request merged**
