### PR TITLE
Data update - January 23, 2016

### PR DESCRIPTION
**Pull request by konklone**
The HTTPS % ticks up again, to **39%**. This is really picking up!

We had 4 presidential libraries move to HTTPS this week, and a couple of EPA redirector domains add and enforce HTTPS support (with HSTS preload headers), as well as a few other domains.

**HTTPS/HSTS adoption:**

* Now forcing HTTPS: `clintonlibrary.gov`,`fordlibrarymuseum.gov`, `nixonlibrary.gov`, `reaganlibrary.gov`, `greengov.gov`, `financialresearch.gov`, `stopalcoholabuse.gov`, `sustainability.gov`, `ustda.gov`

* Now using HTTPS: `clintonlibrary.gov`, `fordlibrarymuseum.gov`, `nixonlibrary.gov`, `reaganlibrary.gov`, `ferc.gov`

* HSTS: `bnl.gov` added a 1-hour HSTS header. `identitytheft.gov` and `robodeidentidad.gov` added HSTS headers that are preload-ready! 

**Improvements to TLS quality:**

* Added TLSv1.2: `identitytheft.gov`, `robodeidentidad.gov`
* Upgraded to SHA-2: `qatesttwai.gov`
* Improved forward secrecy: `nationalchildrensstudy.gov`

### CODE REVIEW

**Comment by konklone** [comment]
Also, for anyone watching these, this is probably my final artisanal hand-crafted Pulse data update. We'll be automating the pipeline in full, hopefully by the time next week's is due, and the data will silently update in place on the production server.

It's certainly possible for us to publish some sort of feed or diff where interested folks can watch things change over time, on pulse.cio.gov. If anyone's interested in that, or has an idea of what would be the most useful thing to show, please ring in!

**Comment by wslack** [comment]
<3

**Comment by jtexnl** [comment]
Awesome! Yes, I'd love to see a way to show progress over time. I'm currently trying to figure out a good way to collect the data from the repo's change history, so let me know if you have any ideas for that.

**Comment by konklone** [comment]
@jtexnl The way I would do it is to create a list of the most recent commit IDs from each data update pull request, repeatedly `git checkout` each one and copy the scan data files into a new directory, and then jump back to `master` and copy the data files in and re-run the part of the script that post-processes the data and publishes them to the `/archive/` directory in S3 with a datestamp set to be that of the scan it belonged to.

That would at least bring the history out of git and into a directory of consistent and predictably named files. 

However, I've really got a lot of momentum right now on refactoring Pulse's data pipeline, and I would wait until that's concluded, and Pulse is deployed and fully automated with a database, before doing surgery on it.

**Pull request merged**
