### PR TITLE
Spell out DAP's name in the donut

### LINKED ISSUE #132: address language in analytics donut
A couple folks in the user testing right now arrive at the site, love the site, and immediately believe that the donut graph on the right represents the *percent of .gov websites that have website analytics at all*.  

To folks seeing this the first time, I absolutely think that will be what's conveyed, a misunderstanding that will be problematic out of the box.  What do folks think about phrasing that could alleviate this?  

* We could say 'Participates in DAP' and strongly call out 'DAP' as a hyperlink that opens in a new tab to the explanation page.  
* We could say 'Participates in the Digital Analytics Program' or 'Participates in GSA Analytics`.  
* Other ideas.

### PR DESCRIPTION
**Pull request by konklone**
Rewords the DAP donut to spell out the name of the program.

screenshot from 2015-05-27 01 16 48

screenshot from 2015-05-27 01 16 54

Fixes #132.

### CODE REVIEW

**Comment by smarina04** [comment]
I like it when it's explicitly stated that it is participation in Digital Analytics Program vs. Analytics.

As for the verbiage piece on the DAP, I would add that it's a central, *shared* web analytics service.... The rest looks great.

**Comment by smarina04** [comment]
Also.. just being picky... would it make sense to have an actual image of the pulse, e.g. http://www.hdwallpapersinn.com/wp-content/uploads/2014/10/1800892.jpg

**Comment by juliaelman** [comment]
@smarina04 thanks for the suggestions! I've made the copy change on the analytics header, see screenshot below:

screen shot 2015-05-27 at 9 26 16 am

screen shot 2015-05-27 at 9 26 31 am


Also, in regards to the pulse image that is something we are definitely exploring in the design. Appreciate the feedback and will keep it in mind for future design decisions :+1:

**Comment by juliaelman** [comment]
Made a few adjustments to the placement of the text and small copy change. Otherwise, looks grand!

**Comment by konklone** [comment]
@smarina04 for clarity, the text change did get made to add _shared_ in https://github.com/18F/pulse/commit/9f77e2f8354cafb11789335d822add7c7352b0f8, the screenshot above just doesn't show it. =)

**Comment by juliaelman** [comment]
@konklone updated the screenshot to show the change too!

**Pull request merged**
