### PR TITLE
Data update - October 22, 2015

### PR DESCRIPTION
**Pull request by konklone**
Three more domains added full HSTS `preload` policies: `ssa.gov`, socialsecurity.gov`, and `segurosocial.gov` (go SSA!).

Some more HSTS on `edpubs.gov` and `fsapubs.gov`, though no `includeSubDomains` policy.

**HTTPS/HSTS adoption:** 

* Now forcing HTTPS: `edpubs.gov`, `arctic.gov`, `banknet.gov`, `edpubs.gov`, `fsapubs.gov`, `nlm.gov`, 

* Now using HTTPS: 

* HSTS: `edpubs.gov`, `fsapubs.gov`, and preload headers on `ssa.gov`, `socialsecurity.gov`, and `segurosocial.gov`

* :-1: - So `tva,gov`'s `max-age` continues to count _down_, as in #318 as well. Extremely strange. I've sent an email to the tva.gov team about it.

### CODE REVIEW

**Comment by djharrity** [comment]
fsapubs.gov has no Qualys grade?

**Comment by konklone** [comment]
@djharrity I'm not sure why Qualys couldn't find it for this scan, but the PR I just filed, #322, shows that Qualys [picked it up this time around as an A](https://github.com/18F/pulse/pull/322/files#diff-8a6c3dff56f511b329d83f629c04d790L431), which will show up on pulse.cio.gov once this PR is merged and deployed.

**Comment by djharrity** [comment]
@konklone Thanks; noticed that each of these domains also don't have Qualys scores: 18f.gov, acus.gov, asc.gov, bfelob.gov, cao.gov, capnhq.gov, cfo.gov, christophercolumbusfoundation.gov, cia.gov, cio.gov, earmarks.gov, everykidinapark.gov, fads.gov, firs.gov, icass.gov, itdashboard.gov, max.gov, ncpc.gov, nlrb.gov, nmsc.gov, nsa.gov, paymentaccuracy.gov, pnl.gov, save.gov, saveaward.gov, sbst.gov, usaspending.gov, ustr.gov, vef.gov, afrh.gov, empowhr.gov, mojavedata.gov, phe.gov

**Comment by konklone** [comment]
@djharrity Yeah, various domains flutter in and out of having their Qualys grade show up each week. Since I control `18f.gov`, I know that we haven't done anything on our end to block Qualys. I suspect that my use of `ssllabs-client` is hitting Qualys API limits, and that need to program in some retry logic when this happens. It's tough to nail down.

If you're specifically looking for domain-level TLS data for your own analysis, you can also look at this spreadsheet, [`sslyze.csv`](https://github.com/18F/pulse/blob/master/data/sslyze.csv), which has some locally calculated TLS configuration data, using `sslyze`, that we don't currently integrate into the site, but which could replace our Qualys integration at some point if we were comfortable dropping their grading methodology (which we'd rather not do).

**Pull request merged**
